// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $post_create from "./routes/post/create.tsx";
import * as $Create from "./islands/Create.tsx";
import * as $VistaIsland from "./islands/VistaIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/post/create.tsx": $post_create,
  },
  islands: {
    "./islands/Create.tsx": $Create,
    "./islands/VistaIsland.tsx": $VistaIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
